version: 2
updates:
  - package-ecosystem: pip
    directory: /fusionsolar-mqtt
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /fusionsolar-mqtt
    schedule:
      interval: weekly
