services:
  fusionsolar-mqtt:
    image: ${FUSIONSOLAR_MQTT_IMAGE:-senzolink/fusionsolar-mqtt:1.0.0}
    container_name: fusionsolar-mqtt
    env_file:
      - .env
    networks:
      - proxy
    restart: unless-stopped

networks:
  proxy:
    external: true
