services:
  fusionsolar-mqtt:
    image: registry.kalamiri.dev/senzolink-fusionsolar-mqtt:1.0.0
    container_name: fusionsolar-mqtt
    env_file:
      - .env
    networks:
      - proxy
    restart: unless-stopped

networks:
  proxy:
    external: true
